name: 'Update from upstream'

on:
  workflow_dispatch:

env:
  GH_CLI_VER: 0.11.1

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout module
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: true
        path: module
    
    - name: Checkout upstream
      uses: actions/checkout@v2.3.1
      with:
        repository: Azure/Enterprise-Scale
        path: es
    - name: Display env
      run: |
        env | sort

    - name: Install gh cli
      run: |
        wget https://github.com/cli/cli/releases/download/v${GH_CLI_VER}/gh_${GH_CLI_VER}_linux_amd64.deb -O /tmp/gh_${GH_CLI_VER}_linux_amd64.deb
        sudo dpkg -i /tmp/gh_${GH_CLI_VER}_linux_amd64.deb

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.1.0
    
    - name: Download jq 1.6
      run: |
        curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o $HOME/jq
        sudo cp -fv $HOME/jq /usr/bin
        sudo chmod a+x /usr/bin/jq
        rm $HOME/jq

    - name: Create branch
      run: |
        git checkout -b autoupdate
        git reset --hard origin/main
      working-directory: $GITHUB_WORKSPACE/module
      
    - name: Convert AzOpsReference
      run: |
        jq --version
        $GITHUB_WORKSPACE/module/scripts/convertazopsreference.sh -r "$GITHUB_WORKSPACE/es/azopsreference" -o "$GITHUB_WORKSPACE/module"
    
    - name: Add changes
      run: |
        if [ $(git status -s) ]; then
          git add *.tf
          git commit -m 'Updated from upstream'
          git push -u origin autoupdate
          gh pr create --title "Autoupdate from upstream" --body "Auto-generated PR" --label "system"
      working-directory: $GITHUB_WORKSPACE/module
          