name: 'Update from upstream'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - '*.tf'
  pull_request:
    paths:
      - '*.tf'

jobs:
  # Plan and Apply job
  update:
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: true
    
    - name: Checkout upstream
      uses: actions/checkout@v2.3.1
      with:
        repository: Azure/Enterprise-Scale
        path: es

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.1.0
    
    - name: Download jq 1.6
      run: |
        curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o $HOME/jq
        sudo cp -f $HOME/jq /usr/bin
        sudo chmod a+x /usr/bin/jq

    - name: Convert AzOpsReference
      run: |
        $HOME/jq --version
        $GITHUB_WORKSPACE/scripts/convertazopsreference.sh -r "$GITHUB_WORKSPACE/es/azopsreference" -o "$GITHUB_WORKSPACE"
